[package]
name = "mcbot-rs"
version = "0.1.0"
authors = ["Mason Ginter <mason@dagint.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.0"
tokio = "0.2.0"

# Waiting on https://github.com/jsvana/async-minecraft-ping/pull/4 
# see https://github.com/jsvana/async-minecraft-ping/issues/3 for details
# async-minecraft-ping = "0.2.1"
async-minecraft-ping = {git = "https://github.com/Hpmason/async-minecraft-ping", branch = "master"}

anyhow = "1.0"
lazy_static = "1.4"