[package]
name = "mcbot-rs"
version = "0.1.0"
authors = ["Mason Ginter <mason@dagint.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.0"
tokio = "0.2.0"
async-minecraft-ping = "0.2.1"
anyhow = "1.0"
lazy_static = "1.4"