ARG APP=mcbot-rs
FROM rust:alpine AS builder
ARG APP

WORKDIR /usr/src/${APP}
COPY . .
RUN apk add alpine-sdk
RUN cargo build --release

FROM alpine 
ARG APP
COPY --from=builder /usr/src/${APP}/target/release/${APP} /usr/local/bin/${APP}
CMD "mcbot-rs"